spring.application.name=employee_management_system

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/employee_management_system
spring.datasource.username=EmployeeManagementSystem
spring.datasource.password=EmployeeManagementSystem@12345678

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

app.security.session-token-validity-hours=12
